### ISSUE TITLE
Collect All Commission Crash

### ISSUE THREAD

**Issue by Suprcode** [Suprcode/Crystal#1018]
> When I click Collect when there are already sold items in the consignment list, a Server Crash error occurs.
> 
> 
> 
>  

@damianday 

 _Originally posted by @Jay-lee-01 in [e8d584f](https://github.com/Suprcode/Crystal/commit/e8d584f823a72282fba13ac8244b57e1d836014c#commitcomment-149196142)_

**Comment by cantea** [comment]
[18/11/2024 19:17:21]: [inner workloop error. Line 0]System.InvalidOperationException: The LinkedList node does not belong to current LinkedList.
   at System.Collections.Generic.LinkedList`1.ValidateNode(LinkedListNode`1 node)
   at System.Collections.Generic.LinkedList`1.Remove(LinkedListNode`1 node)
   at Server.MirObjects.PlayerObject.MarketGetBack(Int32 mode, UInt64 auctionID) in D:\GitHub\LomCn\Source\Server\MirObjects\PlayerObject.cs:line 8305
   at Server.MirNetwork.MirConnection.MarketGetBack(MarketGetBack p) in D:\GitHub\LomCn\Source\Server\MirNetwork\MirConnection.cs:line 1497
   at Server.MirNetwork.MirConnection.ProcessPacket(Packet p) in D:\GitHub\LomCn\Source\Server\MirNetwork\MirConnection.cs:line 507
   at Server.MirNetwork.MirConnection.Process() in D:\GitHub\LomCn\Source\Server\MirNetwork\MirConnection.cs:line 256
   at Server.MirEnvir.Envir.WorkLoop() in D:\GitHub\LomCn\Source\Server\MirEnvir\Envir.cs:line 560

**Comment by damianday** [comment]
Thanks I've found the bug, missed a line or two, will push fix soon
