### ISSUE TITLE
CMain:  Could not load type 'System.Runtime.Serialization.Formatters.Binary.BinaryFormatter' from assembly 'System.Runtime.Serialization.Formatters'.  

### ISSUE THREAD

**Issue by only-ctrlCV** [Suprcode/Crystal#894]
此错误的实例(1)  
 
1。   隐藏调用堆栈 
 
at System.RuntimeTypeHandle.g____PInvoke|78_0(UInt16* name, Int32 throwOnError, Int32 ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
at System.Type.GetType(String typeName, Boolean throwOnError)
at System.Resources.ResourceReader.InitializeBinaryFormatter()
at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
at System.Resources.ResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
at System.Resources.RuntimeResourceSet.ReadValue(ResourceReader reader, Int32 dataPos, Boolean isString, ResourceLocator& locator)
at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
at SlimDX.Resources.get_BlackIcon()
at SlimDX.Windows.RenderForm.Construct(String text)
at SlimDX.Windows.RenderForm..ctor()
at InvokeStub_RenderForm..ctor(Object, Object, IntPtr*)
at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)  

 
有关此错误的帮助  
 
未能找到与此错误相关的帮助主题。 检查 Windows 窗体设计时错误列表   
 

 
有关此错误的论坛帖子  
 
在 MSDN 论坛中搜索与此错误相关的帖子

**Comment by only-ctrlCV** [comment]
> I had the same problem

need vpn download something from cloud，but i gave up

**Comment by cosocc** [comment]
> > I had the same problem
> 
> need vpn download something from cloud，but i gave up

What do you need? I can download it
The project requires Version=4.0.1.0, but the existing version in the .NET Framework is 8.0.224.6711.

**Comment by JevLOMCN** [comment]
[https://www.lomcn.net/wiki/index.php/Getting_Started](https://www.lomcn.net/wiki/index.php/Getting_Started)

**Comment by lymegg** [comment]
This issue arises because SlimDX utilizes the System.Runtime.Serialization.Formatters.Binary.BinaryFormatter method, which has been disabled in .NET 8. As a result, the form cannot be opened. However, I am unsure how to resolve this and am waiting for an expert to provide a solution.

**Comment by damianday** [comment]
One option is to rewrite a custom RenderForm

**Comment by Suprcode** [comment]
Doesn't sound like an issue, theres no need to open the CMain in designer
